[theme]
base = "dark"
primaryColor = "#A78BFA"
backgroundColor = "#060711"
secondaryBackgroundColor = "#10121E"
textColor = "#F8FAFC"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
headless = true
